--- 
git: 
  depth: 1
install:
    - "cd src/test/projects/processors"
    - "mvn install"
    - "cd ../../../.."
    - "mvn install"
cache:
  directories:
  - $HOME/.m2/fr/inria/gforge/spoon/processors/
  - $HOME/.m2/fr/inria/gforge/spoon/processors/spoon-maven-plugin/
before_cache:
  - rm -rf $HOME/.m2/fr/inria/gforge/spoon/processors/spoon-maven-plugin/
jdk: 
  - openjdk8
  - openjdk11

language: java
env:
  - projectName=custom-configuration
  - projectName=hello-world
  - projectName=hello-world-commented
  - projectName=hello-world-config-exception
  - projectName=hello-world-config-exception-ignored
  - projectName=hello-world-exception
  - projectName=hello-world-inputs
  - projectName=hello-world-no-sources
  - projectName=hello-world-spoon-xml
  - projectName=hello-world-with-comments-disabled
  - projectName=hello-world-with-imports
  - projectName=hello-world-with-processor
  - projectName=hello-world-with-properties
  - projectName=javacc-generate
script: 
  - "cd src/test/projects/processors"
  - "mvn install -DskipTests"
  - "cd ../../../.."
  - "mvn install -DskipTests"
  - "cd src/test/projects/"
  - cd $projectName
  - mvn versions:use-next-releases 
  - mvn versions:use-latest-snapshots
  - "mvn package"
  - "mvn clean"
  - "cd ../../../.."
