--- 

pluginversion:
  - 3.5-SNAPSHOT
projectName: 
  - custom-configuration
  - hello-world
  - hello-world-commented
  - hello-world-config-exception
  - hello-world-config-exception-ignored
  - hello-world-exception
  - hello-world-inputs
  - hello-world-no-sources
  - hello-world-spoon-xml
  - hello-world-with-comments-disabled
  - hello-world-with-imports
  - hello-world-with-processor
  - hello-world-with-properties
  - javacc-generate
git: 
  depth: 1
install: true
jdk: 
  - openjdk8
jobs: 
  include: 
    - stage: "unit test"
      script: 
        - "cd src/test/projects/processors"
        - "mvn install -DskipTests -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8"
        - "cd ../../../.."
        - "mvn install -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8"
      jdk: openjdk8
      env: projectName=junitCore

language: java
script: 
  - "cd src/test/projects/processors"
  - "mvn install -DskipTests -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8"
  - "cd ../../../.."
  - "mvn install -DskipTests -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8"
  - "cd src/test/projects/"
  - "cd $projectName"
  - "mvn versions:use-latest-releases"
  - mvn package -"DspoonPlugin.version"=$pluginversion
  - "mvn clean"
  - "cd ../../../.."
stages:
  - unit test
  - test