git:
  depth: 1

language: java 

sudo: required

before_install:
- sudo apt-get install -y xmlstarlet
- SPOON_MAVEN_PLUGIN_VERSION=`xmlstarlet sel -t -v '/_:project/_:version' pom.xml`

jdk:
  - openjdk8

projectName: 
  - hello-world-with-processor
  - javacc-generate
  - hello-world-with-test

install: true

jobs: 
  include:
    - stage: installProcessor
    script: 
      # we need to install the processors first
      - cd src/test/projects/processors
      - mvn install
      - cd ../../../..
    - stage: installProject 
    script:
      - mvn install
    - stage: testProjects
    script:
      - cd src/test/projects/$projectName
      - xmlstarlet edit -L --update '/_:project/_:build/_:plugins/_:plugin/_:version' --value $SPOON_MAVEN_PLUGIN_VERSION pom.xml
      - mvn package
      - mvn clean
      - cd ../../../..
