--- 
env: 
  - projectName=custom-configuration
  - projectName=hello-world
  - projectName=hello-world-commented
  - projectName=hello-world-config-exception
  - projectName=hello-world-config-exception-ignored
  - projectName=hello-world-exception
  - projectName=hello-world-inputs
  - projectName=hello-world-no-sources
  - projectName=hello-world-spoon-xml
  - projectName=hello-world-with-comments-disabled
  - projectName=hello-world-with-imports
  - projectName=hello-world-with-processor
  - projectName=hello-world-with-properties
  - projectName=javacc-generate
git: 
  depth: 1
install: true
jdk: 
  - openjdk8
  - openjdk11
jobs: 
  include: 
    - stage: "unit test"
      script: 
        - "cd src/test/projects/processors"
        - "mvn install -DskipTests"
        - "cd ../../../.."
        - "mvn install"
      jdk: openjdk8
      env: projectName=junitCore

language: java
script: 
  - "cd src/test/projects/processors"
  - "mvn install -DskipTests"
  - "cd ../../../.."
  - "mvn install -DskipTests"
  - "cd src/test/projects/"
  - "cd $projectName"
  - "mvn versions:use-latest-releases"
  - "mvn versions:use-latest-snapshots"
  - "mvn package"
  - "mvn clean"
  - "cd ../../../.."
stages:
  - unit test
  - test